
resources:
  - name: snapshot_promotion
    type: GitRepo
    configuration:
      gitProvider: sivasgithub
      path: shivaraman83/snapshot-promotion
      branches:
        include: main

  - name: promotion_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory

pipelines:
  - name: snapshot_promotion_example
    configuration:
      retentionPolicy:
        maxAgeDays: 30
    steps:
      - name: moverepo
        type: Bash
        configuration:
          integrations:
            - name: artifactory
          inputResources:
            - name: snapshot_promotion

        execution:
          onStart:
            - |
              wget https://download.java.net/java/GA/jdk13.0.1/cec27d702aa74d5a8630c65ae61e4305/9/GPL/openjdk-13.0.1_linux-x64_bin.tar.gz
              tar -xvf openjdk-13.0.1_linux-x64_bin.tar.gz
              mv jdk-13.0.1 /opt/
              JAVA_HOME='/opt/jdk-13.0.1'
              PATH="$JAVA_HOME/bin:$PATH"
              export PATH
              
              wget https://mirrors.estointernet.in/apache/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz
              tar -xvf apache-maven-3.8.5-bin.tar.gz
              mv apache-maven-3.8.5 /opt/
              M2_HOME='/opt/apache-maven-3.8.5'
              PATH="$M2_HOME/bin:$PATH"
              export PATH
              mvn -version
              curl -fL https://install-cli.jfrog.io | sh
          onExecute:
            - echo "Hello World!"
          onComplete:
            - ls -lR
            - jfrog rt build-collect-environment
            - jfrog rt build-publish --detailed-summary $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER

      - name: build_publish
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: moverepo
              status:
                - success
          outputResources:
            - name: promotion_build_info





